GHA failed, trying fewer shards
   > java.lang.IllegalStateException: Gradle was not able to complete
   device setup for: dev30_aosp-atd_x86_Pixel_2
        This could be due to having insufficient resources to provision
	the number of
	     devices requested. Try running the test again and request
	     fewer devices or
	          fewer shards.